name: rentease_app
description: "RentEase - Property Rental Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  flutter_svg: ^2.0.9
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/icon.png"

flutter_native_splash:
  color: "#000000"
  image: "assets/app_icon/icon.png"
  android: true
  ios: true
  fullscreen: true



flutter:
  uses-material-design: true
  assets:
    - assets/app_icon/icon.png
    - assets/landingbg.png
    - assets/logo.png
    - assets/getstarted_imgs/
    - assets/sign_in_up/
    - assets/category_imgs/
    - assets/listings/
    - assets/icons/navbar/
